In [4]:
import numpy as np

In [2]:
%%timeit
[x**2 for x in range(1,1_000_000)]

335 ms ± 7.26 ms per loop (mean ± std. dev. of 7 runs, 1 loop each)


In [5]:
%%timeit
np.arange(1, 1_000_000) ** 2

3.94 ms ± 120 µs per loop (mean ± std. dev. of 7 runs, 100 loops each)


In [6]:
x = [1, 2, 3, 4, 5]
x = np.array(x)
x

array([1, 2, 3, 4, 5])

In [9]:
matrix = np.array([
    [1, 3, 4],
    [4, 5, 6],
    [7, 8, 9]
])

matrix

array([[1, 3, 4],
       [4, 5, 6],
       [7, 8, 9]])

### Slicing Notation

In [13]:
matrix[1:3]

array([[4, 5, 6],
       [7, 8, 9]])

In [17]:
matrix[(matrix > 2) & (matrix < 5)]

array([3, 4, 4])

In [2]:
import numpy as np
## Setup 3
c = [
    [1, 2, 3],
    [4, 5, 6],
    [7, 8, 9]
]

c = np.array(c)

# HINT, you'll first need to make sure that the "c" variable is a numpy array prior to using numpy array methods.
# Exercise 1 - Find the min, max, sum, and product of c.
c.min()
c.max()
c.sum()
c.prod()
# Exercise 2 - Determine the standard deviation of c.
c.std()
# Exercise 3 - Determine the variance of c.
c.var()
# Exercise 4 - Print out the shape of the array c
c.shape
# Exercise 5 - Transpose c and print out transposed result.
c.transpose()
# Exercise 6 - Get the dot product of the array c with c. 
c.dot(c)
# Exercise 7 - Write the code necessary to sum up the result of c times c transposed. Answer should be 261
(c * (c.transpose())).sum()

# Exercise 8 - Write the code necessary to determine the product of c times c transposed. Answer should be 131681894400.
(c * (c.transpose())).prod()

CxC = (c * (c.transpose()))
np.product(c * c.transpose())
(c * c.transpose()).prod()



-1462091776

In [5]:
import numpy as np
c = [
    [1, 2, 3],
    [4, 5, 6],
    [7, 8, 9]
]
c = np.array(c)
print(c.dtype)
print((c * c.transpose()).prod())

c = np.array(c, dtype=np.int64)
print(c.dtype)
print((c * c.transpose()).prod())

int32
-1462091776
int64
131681894400


In [2]:
c.dtype

dtype('int64')